# Generated by Django 2.1.5 on 2019-02-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComboAmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('size', models.CharField(max_length=50, verbose_name='Размер')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('amps', models.CharField(choices=[('lamp', 'Ламповое'), ('transistor', 'Транзисторное'), ('mix', 'Смешанное')], max_length=50, verbose_name='Усиление')),
                ('video', models.CharField(max_length=200, verbose_name='Ссылка на видео')),
                ('img1', models.ImageField(upload_to='combo_amps/')),
                ('img2', models.ImageField(upload_to='combo_amps/')),
                ('img3', models.ImageField(upload_to='combo_amps/')),
                ('img4', models.ImageField(upload_to='combo_amps/')),
            ],
            options={
                'db_table': 'Комбо усилители',
            },
        ),
    ]
