# Generated by Django 2.1.5 on 2019-02-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboamp',
            name='speaker_size',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Размер динамика'),
        ),
    ]
