# Generated by Django 2.1.5 on 2019-02-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_comboamp_speaker_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comboamp',
            name='amps',
            field=models.CharField(choices=[('Лампа', 'Лампа'), ('Транзистор', 'Транзистор'), ('Смешанное', 'Смешанное')], max_length=50, verbose_name='Усиление'),
        ),
    ]
